export const HELLO_WORLD = "HELLO_WORLD";
export const RECEIVE_HELLO_WORLD = "RECEIVE_HELLO_WORLD";
export const POST_CONTACT = "POST_CONTACT";
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const SET_ARTICLE = 'SET_ARTICLE';
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const SET_GALLERY = 'SET_GALLERY';
