export const HELLO_WORLD = "HELLO_WORLD";
export const RECEIVE_HELLO_WORLD = "RECEIVE_HELLO_WORLD";
export const POST_CONTACT = "POST_CONTACT";
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const SET_ARTICLE = 'SET_ARTICLE';
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const SET_GALLERY = 'SET_GALLERY';
export const FETCH_TESTIMONY = 'FETCH_TESTIMONY';
export const SET_TESTIMONY = 'SET_TESTIMONY';
export const FETCH_TEACHER = 'FETCH_TEACHER';
export const SET_TEACHER = 'SET_TEACHER';
export const FETCH_ASSESSMENT = 'FETCH_ASSESSMENT';
export const SET_ASSESSMENT = 'SET_ASSESSMENT';
export const SEND_ASSESSMENT = 'SEND_ASSESSMENT';
export const STUDENT_REGISTER = 'STUDENT_REGISTER';

